env:
  IV: ${{ inputs.imageVersion }}
jobs:
  spilo:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - id: build
        name: build
        run: |
          echo "FROM $IV" >Dockerfile
          echo 'RUN curl -fsSL https://github.com/${{ secrets.DOCKERHUB_USERNAME }}/postgres-operator/raw/action/docker/syncSpiloExt.sh | sh' >>Dockerfile
          echo "imageVersion=${IV##*/}" >>$GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          provenance: false
          pull: true
          push: true
          sbom: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.build.outputs.imageVersion }}
name: syncSpilo
on:
  workflow_dispatch:
    inputs:
      imageVersion:
        default: ghcr.io/zalando/spilo-17:4.0-p3
        description: https://github.com/orgs/zalando/packages?repo_name=spilo
        required: true
        type: string
